### ISSUE TITLE
Hello Nick. Great job.

### ISSUE THREAD

**Issue by tananga** [seenickcode/steadycalendar#3]
I cant wait to take this course. Please make project structure simpler. Can you look at this repo it is so far the best flutter course I had but I hope that yours is gonna be even better, maybe you can copy something https://github.com/MarcusNg/flutter_instagram/tree/47-null-safety

**Comment by seenickcode** [comment]
Hey thanks. Yeah I plan to break up the pages a bit but I will still use a "MVP" (model view provider) pattern, where there is no need for things like "Repositories" since supabase basically offers up our "repository". 

If there is anything in that example you posted that stands out tho, please feel free to join my Discord and we can chat about it. https://discord.gg/dPKTRBdR

**Comment by seenickcode** [comment]
@tananga, check out the latest commit to the 'wip' branch, I organized the code more explicitly. Does that help?

**Comment by tananga** [comment]
I love it. Good job!
